### ISSUE TITLE
Comments do not expand as expected

### ISSUE THREAD

**Issue by skube** [chrisborrowdale/Idiomatic-CSS-Comments-Snippets#9]
This could be my setup since no one seems to be experiencing the same issues.

When I try `com-long` I get the following: 
```css
/**
 * 
 */
```

When trying `com-todo` I get the following:
```css
/**
 * TODO 
 */
```

Also, I have to <kbd>Ctrl</kbd>+<kbd>Space</kbd> to activate since simply tabbing conflicts with Emmet and does not expand.

I'm running Sublime version: 3083 windows x64 channel: stable

**Comment by chrisborrowdale** [comment]
The result for `com-long` is correct, I pushed a fix to the `com-todo` snippet to make it clearer.  

I also have to use <kbd>Ctrl</kbd>+<kbd>Space</kbd> to activate the snippet while using Emmet, and I can't think of a fix for this, I presume it's just an issue while using with Emmet.
